### ISSUE TITLE
IPFS daemon - access to fetch has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by marsrobertson** [P2PModels/wiki#7]
From aragon.chat: https://aragon.chat/channel/random?msg=pTaKs8ci4Fn8EEKqR
Tweet: https://twitter.com/p2pmod/status/1108012049223671813
Testnet: https://rinkeby.aragon.org/#/p2pwiki/0x3fa6887db6254eb94a960843ee37ba1ba9155561/

```
Access to fetch at 'http://localhost:5001/api/v0/swarm/peers?stream-channels=true' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
request.js:80 POST http://localhost:5001/api/v0/swarm/peers?stream-channels=true net::ERR_FAILED
```

![aragon ipfs wiki](https://user-images.githubusercontent.com/44369284/73767278-2a02f400-476f-11ea-8c63-538c2c707c4f.gif)

**Comment by sembrestels** [comment]
Hi @marsrobertson, and thanks for your interest!

Hopefully when #2 is closed we will not need this anymore, but in the meanwhile, because the security policy change in recent versions of IPFS, you have to set up some config in your local node executing the following commands:

```sh
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["null"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs daemon
```

It should be safe enough (your address is still localhost, so your API can't be accessed from another computer), but use it only for testing purposes for the moment.

**Comment by marsrobertson** [comment]
Thanks for that.

Realizing that `git` might be sufficiently decentralized and censorship-resistant for my needs:

Via: https://aragon.chat/channel/random?msg=6E4TZnrkyCzZMHd6y

![image](https://user-images.githubusercontent.com/44369284/73929629-1372af00-48cd-11ea-82aa-fcccc81b0e75.png)
